---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: org1
#  name:	$podName
  name:	peer0
spec:
  replicas: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hyperledger
    spec:
      hostname: peer0
      #subdomain: org1
      volumes:
        - name: msp
          hostPath:
            path: /root/go/src/github.com/hyperledger/fabric/examples/e2e_cli/crypto-config/peerOrganizations/org1/peers/peer0.org1/msp
        - name: tls
          hostPath:
            path: /root/go/src/github.com/hyperledger/fabric/examples/e2e_cli/crypto-config/peerOrganizations/org1/peers/peer0.org1/tls
        - name: run
          hostPath:
            path: /run
      containers:
      - name: peer0
        image: hyperledger/fabric-peer
        volumeMounts:
         - mountPath: /etc/hyperledger/fabric/msp
           readOnly: false
           name: msp
           #subPath: $mspPath
         - mountPath: "/etc/hyperledger/fabric/tls"
           readOnly: false
           name: tls
           #subPath: server.key
         - mountPath: /host/var/run/
           readOnly: false
           name: run
      
        env:
        - name: CORE_VM_ENDPOINT
          value: "unix:///host/var/run/docker.sock"
        - name: CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE
          #value: e2e_default
          value: bridge
        - name: CORE_LOGGING_LEVEL
          value: "DEBUG"
        - name: CORE_PEER_TLS_ENABLED
          value: "true"
        - name: CORE_PEER_GOSSIP_USELEADERELECTION
          value: "true"
        - name: CORE_PEER_GOSSIP_ORGLEADER
          value: "false"
        - name: CORE_PEER_PROFILE_ENABLED
          value: "true"
        - name: CORE_PEER_ADDRESSAUTODETECT
          value: "true" 
        - name: CORE_PEER_TLS_CERT_FILE
          value: /etc/hyperledger/fabric/tls/server.crt
        - name: CORE_PEER_TLS_KEY_FILE
          value: /etc/hyperledger/fabric/tls/server.key
        - name: CORE_PEER_TLS_ROOTCERT_FILE
          value: /etc/hyperledger/fabric/tls/ca.crt
        - name: CORE_PEER_ID
          #value: peer0
          value: peer0.org1
        - name: CORE_PEER_ADDRESS
          #value: peer0:7051
          value: peer0.org1:7051
        - name: CORE_PEER_CHAINCODEADDRESS
          #value: peer0:7052
          value: peer0.org1:7052
        - name: CORE_PEER_CHAINCODELISTENADDRESS
          value: 0.0.0.0:7052
        - name: CORE_PEER_GOSSIP_EXTERNALENDPOINT
          #value: peer0:7051
          value: peer0.org1:7051
        - name: CORE_PEER_LOCALMSPID
          value: Org1MSP
        workingDir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        ports:
         - containerPort: 7051
         - containerPort: 7052
         - containerPort: 7053
        command: ["peer"]
        args: ["node","start"]

---
apiVersion: v1
kind: Service
metadata:
  name: peer0
  namespace: org1
spec:
 selector:
   app: hyperledger
 type: NodePort
 ports:
   - name: externale-listen-endpoint
     protocol: TCP
     port: 7051
     targetPort: 7051
     nodePort: 31051

   - name: chaincode-listen
     protocol: TCP
     port: 7052
     targetPort: 7052
     nodePort: 31052

   - name: event-listen
     protocol: TCP
     port: 7053
     targetPort: 7053
     nodePort: 31053

