---
##dns: orderer.ord
apiVersion: v1
kind: Service
metadata:
  name: orderer
  namespace: ord
  labels:
    app: orderer
##dns: peer0.org1
spec:
 selector:
   app: orderer
 clusterIP: None
 ports:
   - name: externale-listen-endpoint
     protocol: TCP
     port: 7051
     targetPort: 7051
     #nodePort: $nodePort1

   - name: chaincode-listen
     protocol: TCP
     port: 7052
     targetPort: 7052
     #nodePort: $nodePort2

   - name: event-listen
     protocol: TCP
     port: 7053
     targetPort: 7053
     #nodePort: $nodePort3
---

