---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
   name: cli
   namespace: org1
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
       app: cli
    spec:
      containers:
        - name: cli
          image: hyperledger/fabric-tools
          env:
          - name: CORE_PEER_TLS_ENABLED
            value: "true"
          - name: CORE_VM_ENDPOINT
            value: unix:///host/var/run/docker.sock
          - name: GOPATH
            value: /opt/gopath
          - name: CORE_PEER_ADDRESSAUTODETECT
            value: "true" 
#          - name: GODEBUG
#            value: netdns=go
          - name: CORE_LOGGING_LEVEL
            value: DEBUG
          - name: CORE_PEER_ID
            value: cli
          - name: CORE_PEER_ADDRESS
            value: peer0.org1:7051
          - name: CORE_PEER_LOCALMSPID
            value: Org1MSP
          - name: CORE_PEER_LOCALMSPTYPE
            value: bccsp
          - name: CORE_PEER_TLS_CERT_FILE
            value: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1/peers/peer0.org1/tls/server.crt
          - name: CORE_PEER_TLS_KEY_FILE
            value: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1/peers/peer0.org1/tls/server.key
          - name: CORE_PEER_TLS_ROOTCERT_FILE
            value: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1/peers/peer0.org1/tls/ca.crt
          - name: CORE_PEER_MSPCONFIGPATH
            value: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1/users/Admin@org1/msp

          - name: CHANNEL_NAME
            value: mychannel
          #  value: e2e-orderer-syschan 
          - name: TIMEOUT
            value: "100"
          workingDir: /opt/gopath/src/github.com/hyperledger/fabric/peer
          command: ["/bin/bash","-c","--"]
          args: [ 'sleep 3600']
          #args: [ './scripts/script.sh ${CHANNEL_NAME}; sleep $TIMEOUT']
          volumeMounts:
           - mountPath: /host/var/run/
             name: run
           - mountPath: /opt/gopath/src/github.com/hyperledger/fabric/examples/chaincode/go
             name: chaincode
           - mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
             name: crypto
           - mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
             name: scripts
           - mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
             name: artifacts
 
      volumes:
        - name: chaincode
          hostPath: 
            path: /root/go/src/github.com/hyperledger/fabric/examples/chaincode/go
        - name: crypto
          hostPath:
            path:  /root/go/src/github.com/hyperledger/fabric/examples/e2e_cli/crypto-config
        - name: scripts
          hostPath:
            path: /root/go/src/github.com/hyperledger/fabric/examples/e2e_cli/scripts
        - name: artifacts
          hostPath:
            path: /root/go/src/github.com/hyperledger/fabric/examples/e2e_cli/channel-artifacts
        - name: run
          hostPath:
            path: /var/run
